allowed_relationships = [
    # Disease & Condition Relationships
    "CAUSES",
    "CAUSED_BY",
    "ASSOCIATED_WITH",
    "PREDISPOSES_TO",
    "COMPLICATES",
    "COMPLICATED_BY",
    "MANIFESTS_AS",
    "PRESENTS_WITH",
    "DIAGNOSED_BY",
    "INDICATES",
    "SUGGESTS",
    "RULES_OUT",
    "PRECEDES",
    "FOLLOWS",
    "CONCURRENT_WITH",
    "RISK_FACTOR_FOR",
    # Treatment & Drug Relationships
    "TREATS",
    "TREATED_BY",
    "INDICATED_FOR",
    "CONTRAINDICATED_FOR",
    "PRESCRIBED_FOR",
    "ADMINISTERED_VIA",
    "METABOLIZED_BY",
    "INTERACTS_WITH",
    "ENHANCES",
    "INHIBITS",
    "POTENTIATES",
    "SIDE_EFFECT_OF",
    "ADVERSE_REACTION_TO",
    "ALLERGIC_TO",
    # Anatomical & Physiological
    "LOCATED_IN",
    "PART_OF",
    "CONTAINS",
    "ADJACENT_TO",
    "CONNECTS_TO",
    "INNERVATES",
    "SUPPLIES",
    "DRAINS",
    "AFFECTS",
    "AFFECTED_BY",
    "FUNCTIONS_IN",
    "DISRUPTS",
    # Genetic & Molecular
    "ENCODES",
    "ENCODED_BY",
    "REGULATES",
    "REGULATED_BY",
    "EXPRESSED_IN",
    "MUTATED_IN",
    "VARIANT_OF",
    "HOMOLOGOUS_TO",
    "INTERACTS_WITH",
    "BINDS_TO",
    "CATALYZES",
    "SUBSTRATE_OF",
    # Clinical & Diagnostic
    "DIAGNOSED_WITH",
    "TESTS_FOR",
    "MEASURES",
    "EVALUATES",
    "MONITORS",
    "SCREENS_FOR",
    "DETECTS",
    "CONFIRMS",
    "DIFFERENTIATES",
    "EXCLUDES",
    "SUPPORTS_DIAGNOSIS",
    # Temporal Relationships
    "OCCURS_BEFORE",
    "OCCURS_AFTER",
    "OCCURS_DURING",
    "TEMPORAL_SEQUENCE",
    "CHRONIC_FORM_OF",
    "ACUTE_FORM_OF",
    "STAGE_OF",
    "PHASE_OF",
    "PROGRESSION_OF",
    # Hierarchical & Classification
    "IS_A",
    "SUBTYPE_OF",
    "PARENT_OF",
    "CHILD_OF",
    "BELONGS_TO",
    "MEMBER_OF",
    "CLASSIFIED_AS",
    "CATEGORIZED_AS",
    "SPECIALIZATION_OF",
    "GENERALIZATION_OF",
    # Research & Evidence
    "STUDIED_IN",
    "EVIDENCE_FOR",
    "SUPPORTED_BY",
    "CONTRADICTED_BY",
    "REPORTED_IN",
    "PUBLISHED_IN",
    "REFERENCED_BY",
    "CITES",
    # Quantitative Relationships
    "INCREASES",
    "DECREASES",
    "CORRELATES_WITH",
    "PROPORTIONAL_TO",
    "DOSE_DEPENDENT",
    "TIME_DEPENDENT",
    "AGE_DEPENDENT",
    "SEVERITY_RELATED",
    "FREQUENCY_RELATED",
    # Population & Epidemiological
    "PREVALENT_IN",
    "INCIDENCE_IN",
    "ENDEMIC_TO",
    "EPIDEMIC_IN",
    "DEMOGRAPHIC_FACTOR",
    "GEOGRAPHIC_DISTRIBUTION",
    "SEASONAL_PATTERN",
    # Outcome & Prognosis
    "PREDICTS",
    "PROGNOSTIC_FOR",
    "OUTCOME_OF",
    "SURVIVAL_FACTOR",
    "RECOVERY_FROM",
    "REMISSION_OF",
    "RELAPSE_OF",
    "RECURRENCE_OF",
    # Preventive & Prophylactic
    "PREVENTS",
    "PREVENTED_BY",
    "PROTECTIVE_AGAINST",
    "PROPHYLAXIS_FOR",
    "VACCINATION_AGAINST",
    "SCREENING_FOR",
    "RISK_REDUCTION",
    # Mechanism & Pathway
    "MECHANISM_OF",
    "PATHWAY_OF",
    "UPSTREAM_OF",
    "DOWNSTREAM_OF",
    "ACTIVATES",
    "DEACTIVATES",
    "MODULATES",
    "MEDIATES",
]
